2017-01-13 11:31:29 local_test_v2.py[line:578] INFO start
2017-01-13 11:31:29 local_test_v2.py[line:580] INFO access_20170103122000.log
2017-01-13 11:31:29 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:30 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:30 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:30 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:30 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:30 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:30 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:35 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:35 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:35 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:35 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:35 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:35 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:35 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:39 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:31:39 local_test_v2.py[line:590] ERROR <type 'exceptions.Exception'>:
2017-01-13 11:31:39 local_test_v2.py[line:580] INFO access_20170103160500.log
2017-01-13 11:31:39 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:39 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:39 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:39 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:39 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:39 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:39 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:44 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:44 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:44 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:44 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:44 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:44 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:44 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:49 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:31:49 local_test_v2.py[line:590] ERROR <type 'exceptions.Exception'>:
2017-01-13 11:31:49 local_test_v2.py[line:580] INFO access_20170103164000.log
2017-01-13 11:31:49 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:49 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:49 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:49 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:49 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:49 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:49 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:54 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:54 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:54 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:54 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:54 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:31:54 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:31:54 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:31:59 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:31:59 local_test_v2.py[line:590] ERROR <type 'exceptions.Exception'>:
